# Generated by Django 5.0.4 on 2024-05-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_additional_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_balance',
            name='original_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
